apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: wireguard-key
  namespace: wireguard
spec:
  path: kvv2/cnp-vpn/wireguard
  vaultRole: wireguard-role
  keys:
    - privatekey
  type: Opaque
