apiVersion: guard.3istor.com/v1alpha1
kind: OffhoursSchedule
metadata:
  name: roadmap-schedule
  namespace: roadmap
spec:
  targetRefs:
    - name: roadmap
    - name: roadmap-postgres
  sleepAt: "0 1 * * *"
  wakeAt: "0 7 * * *"
  timezone: "Europe/Paris"
