apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: roadmap-secrets
  namespace: roadmap
spec:
  path: kvv2/roadmap/config
  vaultRole: roadmap-role
  type: Opaque
  keys:
    - database-url
    - database-password
    - notion-api-key
    - notion-members-db-id
    - notion-projects-db-id
    - notion-events-db-id
    - notion-tasks-db-id
    - webhook-secret
    - cron-secret
