apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: qcm-secrets
  namespace: qcm
spec:
  path: kvv2/qcm/config
  vaultRole: qcm-role
  type: Opaque
  keys:
    - DATABASE_URL
    - NEXTAUTH_SECRET
    - KEYCLOAK_CLIENT_SECRET
