image:
  repository: ghcr.io/3-istor/qcm
  tag: "latest"
  pullPolicy: Always
ingress:
  enabled: false
env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_PUBLIC_APP_URL
    value: "https://qcm.3istor.com"
  - name: NEXTAUTH_URL
    value: "https://qcm.3istor.com"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: qcm-secrets
        key: DATABASE_URL
  - name: NEXTAUTH_SECRET
    valueFrom:
      secretKeyRef:
        name: qcm-secrets
        key: NEXTAUTH_SECRET
  - name: KEYCLOAK_CLIENT_ID
    value: "3-istor-openid"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: qcm-secrets
        key: KEYCLOAK_CLIENT_SECRET
  - name: KEYCLOAK_ISSUER
    value: "https://auth.3istor.com/realms/3istor"
