apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - namespace.yaml
  - deployment.yaml

secretGenerator:
  - name: cloudflared-token
    namespace: cloudflared
    literals:
      - token="CHANGE_ME_AVEC_TON_TOKEN_CLOUDFLARE"
