apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  path: kvv2/cloudflared/token
  vaultRole: cloudflared-role
  keys:
    - token
  type: Opaque
