apiVersion: guard.3istor.com/v1alpha1
kind: OffhoursSchedule
metadata:
  name: linmap-bot-schedule
  namespace: linmap-bot
spec:
  targetRefs:
    - name: linmap-bot-api
    - name: linmap-bot-bot
  sleepAt: "0 1 * * *"
  wakeAt: "0 7 * * *"
  timezone: "Europe/Paris"
