apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: linmap-bot-secrets
  namespace: linmap-bot
spec:
  path: kvv2/linmap-bot/config
  vaultRole: linmap-bot-role
  type: Opaque
  keys:
    - LINEAR_API_KEY
    - DISCORD_TOKEN
    - GOOGLE_APPLICATION_CREDENTIALS_JSON
