apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: envoy-demo-app-secret
  namespace: demo-app
spec:
  path: kvv2/demo-app/envoy-auth
  vaultRole: demo-app-role
  keys:
    - client-secret
  type: Opaque
