routes:
  demo-frontend:
    targetService:
      name: "kube-classes-svc"
      port: 80
    ingress:
      hostname: "demo.3istor.com"
    auth:
      enabled: true
      allowedGroups:
        - "member"
        - "infra"
      vault:
        path: "kvv2/demo-app/envoy-auth"
        role: "demo-app-role"
