apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: observability-secrets
  namespace: observability
spec:
  path: kvv2/observability/config
  vaultRole: observability-role
  type: Opaque
  keys:
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
    - GRAFANA_ADMIN_PASSWORD
