apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - demo-app.yaml
  - gateway-infra.yaml
  - kyverno.yaml
  - keycloak.yaml
  - envoy-gateway.yaml
  - vault-secrets-operator.yaml
  - vault.yaml
  - argocd.yaml
