apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roadmap
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true

    argocd-image-updater.argoproj.io/image-list: roadmap=ghcr.io/3-istor/roadmap
    argocd-image-updater.argoproj.io/roadmap.update-strategy: digest
    argocd-image-updater.argoproj.io/roadmap.allow-tags: regexp:^sha-[a-f0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/3-Istor/K3s.git
    targetRevision: HEAD
    path: k8s/config/roadmap
  destination:
    name: in-cluster
    namespace: roadmap
