apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:v5.7.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: status-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: gatus-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus-svc
  namespace: status
spec:
  selector:
    app: gatus
  ports:
    - port: 80
      targetPort: 8080
