apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: status-secrets
  namespace: status
spec:
  path: kvv2/status/config
  vaultRole: status-role
  type: Opaque
  keys:
    - DISCORD_WEBHOOK_URL
    - client-secret
