apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  namespace: argocd
spec:
  path: kvv2/argocd/oidc
  type: Opaque
  reconcileStrategy: Merge
  keys:
    - oidc.keycloak.clientSecret
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  path: kvv2/argocd/github-bot
  vaultRole: argocd-role
  type: Opaque
  keys:
    - username
    - password
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cnp-portal-github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  path: kvv2/argocd/github-app
  vaultRole: argocd-role
  type: Opaque
  keys:
    - type
    - url
    - githubAppID
    - githubAppInstallationID
    - githubAppPrivateKey
