alloy:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1000Mi

  configMap:
    create: true
    content: |-
      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.source.kubernetes "local_logs" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.process.add_tenant.receiver]
      }

      loki.process "add_tenant" {
        stage.match {
          selector = "{namespace=~\"project-.*|demo-app|n8n\"}"
          stage.tenant {
            label = "tenant"
          }
        }
        forward_to = [loki.write.local_loki.receiver]
      }

      loki.write "local_loki" {
        endpoint {
          url       = "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"
          tenant_id = "default"
        }
      }

      prometheus.scrape "local_metrics" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [prometheus.remote_write.vmauth.receiver]
      }

      prometheus.operator.podmonitors "local_pods" {
        forward_to = [prometheus.remote_write.vmauth.receiver]
      }

      prometheus.operator.servicemonitors "local_services" {
        forward_to = [prometheus.remote_write.vmauth.receiver]
      }

      prometheus.remote_write "vmauth" {
        endpoint {
          url = "http://vm-victoria-metrics-cluster-vminsert.observability.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
        }
      }
