replicas: 1

deploymentStrategy:
  type: Recreate

envFromSecret: observability-secrets

grafana.ini:
  security:
    admin_password: $__env{GRAFANA_ADMIN_PASSWORD}
  server:
    root_url: "https://grafana.3istor.com"
  auth.generic_oauth:
    enabled: true
    name: "3Istor ID"
    allow_sign_up: true
    client_id: "3-istor-openid"
    client_secret: $__env{OIDC_CLIENT_SECRET}
    scopes: "openid profile email roles groups"
    auth_url: "https://auth.3istor.com/realms/3istor/protocol/openid-connect/auth"
    token_url: "https://auth.3istor.com/realms/3istor/protocol/openid-connect/token"
    api_url: "https://auth.3istor.com/realms/3istor/protocol/openid-connect/userinfo"
    role_attribute_path: "contains(groups[*], 'infra') && 'Admin' || contains(groups[*], 'member') && 'Viewer'"

persistence:
  enabled: true
  storageClassName: "ceph-block"
  size: 2Gi

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

# We don't provision datasources automatically because you will create them per Grafana Organization (Client A, Client B) manually to enforce multi-tenancy.
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: "http://vm-victoria-metrics-cluster-vmselect.observability.svc.cluster.local:8481/select/0/prometheus"
        access: proxy
        isDefault: true
        jsonData:
          prometheusType: "Prometheus"
          manageAlerts: false

      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        url: "http://alertmanager.observability.svc.cluster.local:9093"
        access: proxy
        jsonData:
          implementation: prometheus

# Configure dashboard providers.
# ref: http://docs.grafana.org/administration/provisioning/#dashboards
# `path` must be /var/lib/grafana/dashboards/<provider_name>
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default

      - name: "envoy-gateway"
        orgId: 1
        folder: "Envoy Gateway"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/envoy-gateway

      - name: "kubernetes"
        orgId: 1
        folder: "Kubernetes"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes

      - name: "infrastructure"
        orgId: 1
        folder: "Infrastructure"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/infrastructure

dashboards:
  envoy-gateway:
    # Doc: https://gateway.envoyproxy.io/docs/tasks/observability/gateway-api-metrics/#dashboards
    # Grafana Links: https://grafana.com/grafana/dashboards/<gnetId>
    gateway-api-state:
      gnetId: 19433
      revision: 2
      datasource: Prometheus
    gateway-http-metrics:
      gnetId: 19432
      revision: 2
      datasource: Prometheus
    envoy-proxy-metrics:
      gnetId: 19434
      revision: 2
      datasource: Prometheus

  kubernetes:
    k8s-cluster:
      gnetId: 15757
      revision: 43
      datasource: Prometheus
    k8s-namespaces:
      gnetId: 15758
      revision: 46
      datasource: Prometheus
    k8s-nodes:
      gnetId: 15759
      revision: 40
      datasource: Prometheus
    k8s-pods:
      gnetId: 15760
      revision: 39
      datasource: Prometheus

  infrastructure:
    node-exporter-full:
      gnetId: 1860
      revision: 45
      datasource: Prometheus
