apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mepa-app

resources:
  - namespace.yaml
  - secrets.yaml
  - offhours-guard.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: ia-clair
    repo: oci://ghcr.io/3-istor/charts
    version: 0.1.1
    releaseName: mepa-app
    namespace: mepa-app
    valuesFile: mepa-app-values.yaml

  - name: secure-route
    releaseName: mepa-app-routes
    namespace: mepa-app
    valuesFile: values-secure-route.yaml
