apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: mepa-app-secrets
  namespace: mepa-app
spec:
  path: kvv2/mepa-app/config
  vaultRole: mepa-role
  type: Opaque
  keys:
    - GEMINI_API_KEY
    - FLASK_SECRET_KEY
