routes:
  ia-clair:
    hostnames:
      - "mepa.3istor.com"
    rules:
      - backendRefs:
          - name: mepa
            port: 80
    auth:
      enabled: true
      vault:
        path: "kvv2/mepa-app/envoy-auth"
        role: "mepa-role"
