apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph
spec:
  path: kvv2/rook-ceph/mon-secret
  vaultRole: rook-ceph-role
  type: Opaque
  keys:
    - cluster-name
    - fsid
    - admin-secret
    - mon-secret
    - ceph-username
    - ceph-secret
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph
spec:
  path: kvv2/rook-ceph/csi-node
  vaultRole: rook-ceph-role
  type: Opaque
  keys:
    - userID
    - userKey
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph
spec:
  path: kvv2/rook-ceph-role
  vaultRole: rook-ceph-role
  type: Opaque
  keys:
    - userID
    - userKey
