# This configures the CSI drivers to point to the external OpenStack Ceph
toolbox:
  enabled: false

cephClusterSpec:
  external:
    enable: true

  crashCollector:
    disable: true

  # wget https://raw.githubusercontent.com/rook/rook/master/deploy/examples/create-external-cluster-resources.py

  # sudo cephadm shell   -v /home/pae-node-1:/mnt \
  #   -- python3 /mnt/create-external-cluster-resources.py \
  #   --namespace rook-ceph   --rbd-data-pool-name volumes \
  #   --format bash > external-cluster-details.sh

  dataDirHostPath: /var/lib/rook

cephBlockPools: []
cephFileSystems: []
cephObjectStores: []
