replicaCount: 1

image:
  backend:
    repository: ghcr.io/3-istor/cmp-backend
    pullPolicy: Always
    tag: "latest"
  frontend:
    repository: ghcr.io/3-istor/cmp-frontend
    pullPolicy: Always
    tag: "latest"

frontend:
  apiUrl: "https://cmp.3istor.com/api"

ingress:
  enabled: false

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsUser: 1001

resources:
  backend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  frontend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

persistence:
  enabled: true
  storageClass: "local-path"
  backend:
    size: 2Gi
    accessMode: ReadWriteOnce

env:
  backend:
    DATABASE_URL: "sqlite:////app/db/arcl.db"

secrets:
  create: false
