apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arcl-cmp

resources:
  - namespace.yaml
  - secrets.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: arcl-cmp
    repo: oci://ghcr.io/3-istor/charts
    version: 0.1.2
    releaseName: arcl-cmp
    namespace: arcl-cmp
    valuesFile: cmp-values.yaml

  - name: secure-route
    releaseName: cmp-routes
    namespace: arcl-cmp
    valuesFile: values-secure-route.yaml
