apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arcl-cmp-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/credentials
  vaultRole: arcl-cmp-role
  type: Opaque
  keys:
    - os-auth-url
    - os-username
    - os-password
    - os-project-name
    - os-user-domain-name
    - os-project-domain-name
    - os-endpoint-type
    - aws-access-key-id
    - aws-secret-access-key
    - aws-region
    - aws-s3-bucket
    - aws-s3-key-prefix
    - avatars-s3-access-key-id
    - avatars-s3-secret-access-key
    - avatars-s3-endpoint
    - avatars-s3-bucket
    - avatars-s3-region
    - avatars-s3-public-url-base
    - cloudflare-api-token
    - cloudflare-zone-id
    - discord-webhook-url
    - cloudflare-account-id
    - github-app-id
    - github-app-private-key
    - github-installation-id
    - github-registry-username
    - github-registry-token
    - keycloak-admin-username
    - keycloak-admin-password
    - vault-token
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arcl-cmp-frontend-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/frontend
  vaultRole: arcl-cmp-role
  keys:
    - nextauth-secret
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cmp-route-envoy-auth-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/envoy-auth
  vaultRole: arcl-cmp-role
  keys:
    - client-secret
  type: Opaque
