apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-pull-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/ghcr
  vaultRole: arcl-cmp-role
  type: kubernetes.io/dockerconfigjson
  keys:
    - .dockerconfigjson
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arcl-cmp-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/credentials
  vaultRole: arcl-cmp-role
  type: Opaque
  keys:
    - aws-access-key-id
    - aws-region
    - aws-s3-bucket
    - aws-s3-key-prefix
    - aws-secret-access-key
    - os-auth-url
    - os-password
    - os-project-domain-name
    - os-project-name
    - os-user-domain-name
    - os-username
