apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arcl-cmp-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/credentials
  vaultRole: arcl-cmp-role
  type: Opaque
  keys:
    - aws-access-key-id
    - aws-region
    - aws-s3-bucket
    - aws-s3-key-prefix
    - aws-secret-access-key
    - os-auth-url
    - os-password
    - os-project-domain-name
    - os-project-name
    - os-user-domain-name
    - os-username
    - avatars-s3-access-key-id
    - avatars-s3-secret-access-key
    - avatars-s3-endpoint
    - avatars-s3-bucket
    - avatars-s3-region
    - avatars-s3-public-url-base
    - cloudflare-api-token
    - cloudflare-zone-id
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: envoy-cmp-auth-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/envoy-auth
  vaultRole: arcl-cmp-role
  keys:
    - client-secret
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arcl-cmp-frontend-secret
  namespace: arcl-cmp
spec:
  path: kvv2/arcl-cmp/frontend
  vaultRole: arcl-cmp-role
  keys:
    - nextauth-secret
  type: Opaque
