apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: mepa-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "mepa-app"
      images:
        - alias: "mepa-app"
          imageName: "ghcr.io/3-istor/mepa"

          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"

          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^sha-[a-f0-9]+$"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          branch: "main"
          writeBackTarget: "helmvalues:/k8s/config/mepa-app/mepa-app-values.yaml"
          pullRequest:
            github: {}
